FROM python:3.11-slim

ENV PIP_NO_CACHE_DIR=1
RUN pip install --upgrade pip

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY ocpp_ws.py .
COPY app ./app

VOLUME ["/data"]

EXPOSE 9000

CMD ["python", "ocpp_ws.py"]
