FROM python:3.11-slim

ENV PIP_NO_CACHE_DIR=1
RUN pip install --upgrade pip

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY api.py .
COPY app ./app

VOLUME ["/data"]

EXPOSE 8000

CMD ["python", "api.py"]
