[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:redis]
command=/usr/bin/redis-server --bind 127.0.0.1 --port 6379 --requirepass %(ENV_REDIS_PASSWORD)s --appendonly yes
autostart=true
autorestart=true
startsecs=2
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:api]
directory=/app
command=python api.py
environment=REDIS_HOST="127.0.0.1",REDIS_PORT="6379",REDIS_DB="0",REDIS_PASSWORD="%(ENV_REDIS_PASSWORD)s",API_PORT="8000",APP_SECRET="%(ENV_APP_SECRET)s"
autostart=true
autorestart=true
startsecs=3
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:ocpp]
directory=/app
command=python ocpp_ws.py
environment=REDIS_HOST="127.0.0.1",REDIS_PORT="6379",REDIS_DB="0",REDIS_PASSWORD="%(ENV_REDIS_PASSWORD)s",OCPP_PORT="9000",PORTAL_TAGS_GLOBAL="%(ENV_PORTAL_TAGS_GLOBAL)s"
autostart=true
autorestart=true
startsecs=3
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
startsecs=2
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

